Cell 1 - Import Libraries

In [36]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

Cell 2 - Load Dataset

In [37]:
branches = pd.read_csv("../data/raw/branches.csv")
customers = pd.read_csv("../data/raw/customers.csv")
inventory = pd.read_csv("../data/raw/inventory_master.csv")
invoices = pd.read_csv("../data/raw/invoices.csv")
payments = pd.read_csv("../data/raw/payments.csv")
products = pd.read_csv("../data/raw/products.csv")
po_header = pd.read_csv("../data/raw/purchase_orders_header.csv")
po_lines = pd.read_csv("../data/raw/purchase_orders_lines.csv")
sales_header = pd.read_csv("../data/raw/sales_orders_header.csv")
sales_lines = pd.read_csv("../data/raw/sales_orders_lines.csv")
stock = pd.read_csv("../data/raw/stock_ledger.csv")
suppliers = pd.read_csv("../data/raw/suppliers.csv")

Cell 3 - Store in Dictionary

In [38]:
datasets = {
    "Branches": branches,
    "Customers": customers,
    "Inventory": inventory,
    "Invoices": invoices,
    "Payments": payments,
    "Products": products,
    "Purchase Header": po_header,
    "Purchase Lines": po_lines,
    "Sales Header": sales_header,
    "Sales Lines": sales_lines,
    "Stock Ledger": stock,
    "Suppliers": suppliers
}

Cell 4 - Standardize Column Names

In [39]:
for name, df in datasets.items():

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

print("Column names standardized.")

Column names standardized.

Cell 5 - Remove Duplicate Rows

In [40]:
duplicate_summary = []

for name, df in datasets.items():

    before = len(df)

    df.drop_duplicates(inplace=True)

    after = len(df)

    duplicate_summary.append({
        "Dataset": name,
        "Duplicates Removed": before - after
    })

pd.DataFrame(duplicate_summary)

            Dataset  Duplicates Removed
0          Branches                   0
1         Customers                   0
2         Inventory                   0
3          Invoices                   0
4          Payments                   0
5          Products                   0
6   Purchase Header                   0
7    Purchase Lines                   0
8      Sales Header                   0
9       Sales Lines                   0
10     Stock Ledger                   0
11        Suppliers                   0

Cell 6 - Missing Value Report

In [41]:
missing_report = []

for name, df in datasets.items():

    missing_report.append({
        "Dataset": name,
        "Missing Values": df.isnull().sum().sum()
    })

pd.DataFrame(missing_report)

            Dataset  Missing Values
0          Branches               0
1         Customers               0
2         Inventory               0
3          Invoices               0
4          Payments               0
5          Products               0
6   Purchase Header            2370
7    Purchase Lines               0
8      Sales Header               0
9       Sales Lines               0
10     Stock Ledger               0
11        Suppliers               0

Cell 7 - Fill Missing Values

In [42]:
for name, df in datasets.items():

    for col in df.columns:

        # Numeric columns
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].fillna(df[col].median())

        # Date columns
        elif pd.api.types.is_datetime64_any_dtype(df[col]):
            # Leave missing dates as NaT
            pass

        # Text / categorical columns
        else:
            df[col] = df[col].fillna("Unknown")

print("Missing values handled.")

Missing values handled.

Cell 8 - Remove Extra Spaces

In [43]:
for name, df in datasets.items():

    text_cols = df.select_dtypes(include="object").columns

    for col in text_cols:

        df[col] = df[col].str.strip()

print("Whitespace removed.")

Whitespace removed.

C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1760072880.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

Cell 9 - Convert Text to Title Case

In [44]:
for name, df in datasets.items():

    text_cols = df.select_dtypes(include="object").columns

    for col in text_cols:

        df[col] = df[col].str.title()

print("Text standardized.")

C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns
C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

Text standardized.

C:\Users\RIYA\AppData\Local\Temp\ipykernel_3184\1511504888.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

Cell 10 - Convert Date Columns

In [45]:
for name, df in datasets.items():

    for col in df.columns:

        if "date" in col:

            df[col] = pd.to_datetime(
                df[col],
                errors="coerce"
            )

print("Date columns converted.")

Date columns converted.

Cell 11 - Dataset Quality Check

In [46]:
quality = []

for name, df in datasets.items():

    quality.append({

        "Dataset": name,

        "Rows": len(df),

        "Columns": len(df.columns),

        "Missing": df.isnull().sum().sum(),

        "Duplicates": df.duplicated().sum()

    })

quality_df = pd.DataFrame(quality)

quality_df

            Dataset    Rows  Columns  Missing  Duplicates
0          Branches       6       13        0           0
1         Customers     500       15        0           0
2         Inventory     180        8        0           0
3          Invoices   18033       10        0           0
4          Payments   19257        5        0           0
5          Products      30       23        0           0
6   Purchase Header   24000       10     2370           0
7    Purchase Lines  155495        9        0           0
8      Sales Header   20000       11        0           0
9       Sales Lines  130402        9        0           0
10     Stock Ledger  237230        9        0           0
11        Suppliers       8       12        0           0

Cell 12 - Invalid Numeric Values

In [47]:
for name, df in datasets.items():

    numeric = df.select_dtypes(include=np.number)

    print("="*60)

    print(name)

    for col in numeric.columns:

        negative = (df[col] < 0).sum()

        print(col, ":", negative, "negative values")

============================================================
Branches
manager_id : 0 negative values
total_employees : 0 negative values
avg_monthly_revenue : 0 negative values
monthly_operational_cost : 0 negative values
market_demand_index : 0 negative values
============================================================
Customers
pincode : 0 negative values
credit_limit : 0 negative values
current_balance : 0 negative values
total_purchase_value : 0 negative values
customer_rating : 0 negative values
============================================================
Inventory
opening_stock : 0 negative values
reorder_level : 0 negative values
safety_stock : 0 negative values
max_stock : 0 negative values
current_stock : 0 negative values
============================================================
Invoices
total_order_value : 0 negative values
total_gst_amount : 0 negative values
grand_total : 0 negative values
============================================================
Payments
payment_amount : 0 negative values
============================================================
Products
unit_cost : 0 negative values
unit_price : 0 negative values
margin_percentage : 0 negative values
gst_rate : 0 negative values
weight_kg : 0 negative values
warranty_months : 0 negative values
reorder_level : 0 negative values
safety_stock : 0 negative values
max_stock_level : 0 negative values
lead_time_days : 0 negative values
last_purchase_price : 0 negative values
============================================================
Purchase Header
total_cost : 0 negative values
total_gst_amount : 0 negative values
grand_total : 0 negative values
============================================================
Purchase Lines
line_number : 0 negative values
quantity : 0 negative values
unit_cost : 0 negative values
gst_rate : 0 negative values
line_total : 0 negative values
gst_amount : 0 negative values
line_grand_total : 0 negative values
============================================================
Sales Header
total_order_value : 0 negative values
total_gst_amount : 0 negative values
grand_total : 0 negative values
============================================================
Sales Lines
line_number : 0 negative values
quantity : 0 negative values
unit_price : 0 negative values
gst_rate : 0 negative values
line_total : 0 negative values
gst_amount : 0 negative values
line_grand_total : 0 negative values
============================================================
Stock Ledger
quantity : 0 negative values
running_balance : 0 negative values
============================================================
Suppliers
pincode : 0 negative values
lead_time_days : 0 negative values
reliability_score : 0 negative values
import_duty_rate : 0 negative values

Cell 13 - Feature Engineering

In [48]:
for name, df in datasets.items():

    date_columns = [col for col in df.columns if "date" in col]

    for col in date_columns:

        df[col] = pd.to_datetime(df[col], errors="coerce")

        df[f"{col}_year"] = df[col].dt.year
        df[f"{col}_month"] = df[col].dt.month

print("Feature engineering completed.")

Feature engineering completed.

Cell 14 - Save Cleaned Dataset

In [49]:
import os

os.makedirs("../data/cleaned", exist_ok=True)

for name, df in datasets.items():

    filename = name.lower().replace(" ", "_")

    df.to_csv(
        f"../data/cleaned/{filename}.csv",
        index=False
    )

print("Cleaned datasets saved.")

Cleaned datasets saved.

Cell 15 - Cleaning Summary

In [50]:
summary = pd.DataFrame({

    "Dataset":[x for x in datasets.keys()],

    "Rows":[df.shape[0] for df in datasets.values()],

    "Columns":[df.shape[1] for df in datasets.values()]

})

summary

            Dataset    Rows  Columns
0          Branches       6       13
1         Customers     500       17
2         Inventory     180        8
3          Invoices   18033       14
4          Payments   19257        7
5          Products      30       25
6   Purchase Header   24000       16
7    Purchase Lines  155495        9
8      Sales Header   20000       15
9       Sales Lines  130402        9
10     Stock Ledger  237230       11
11        Suppliers       8       12